[programs.devnet]
gifwall = "6Nne2tQqiuXMnw24cqbw3ui2Mv55tcX6Pxcn2UyJQ98y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/hjeldin/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
